/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: .\bind.swigcxx

package bind

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef long long swig_type_12;
typedef long long swig_type_13;
typedef long long swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
typedef long long swig_type_17;
typedef long long swig_type_18;
typedef _gostring_ swig_type_19;
typedef _gostring_ swig_type_20;
typedef _gostring_ swig_type_21;
typedef _gostring_ swig_type_22;
typedef _gostring_ swig_type_23;
typedef _gostring_ swig_type_24;
typedef _gostring_ swig_type_25;
typedef _gostring_ swig_type_26;
typedef _gostring_ swig_type_27;
typedef _gostring_ swig_type_28;
typedef _gostring_ swig_type_29;
typedef _gostring_ swig_type_30;
typedef _gostring_ swig_type_31;
typedef _gostring_ swig_type_32;
typedef _gostring_ swig_type_33;
typedef _gostring_ swig_type_34;
typedef _gostring_ swig_type_35;
typedef _gostring_ swig_type_36;
typedef _gostring_ swig_type_37;
typedef _gostring_ swig_type_38;
typedef _gostring_ swig_type_39;
typedef _gostring_ swig_type_40;
typedef _gostring_ swig_type_41;
extern void _wrap_Swig_free_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_bind_a8cb6205d990f6b5(swig_intgo arg1);
extern uintptr_t _wrap_new_ActionVec__SWIG_0_bind_a8cb6205d990f6b5(void);
extern uintptr_t _wrap_new_ActionVec__SWIG_1_bind_a8cb6205d990f6b5(swig_type_1 arg1);
extern uintptr_t _wrap_new_ActionVec__SWIG_2_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern swig_type_2 _wrap_ActionVec_size_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern swig_type_3 _wrap_ActionVec_capacity_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_ActionVec_reserve_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_4 arg2);
extern _Bool _wrap_ActionVec_isEmpty_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_ActionVec_clear_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_ActionVec_add_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ActionVec_get_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_ActionVec_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_intgo arg2, uintptr_t arg3);
extern void _wrap_delete_ActionVec_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern uintptr_t _wrap_new_StringVec__SWIG_0_bind_a8cb6205d990f6b5(void);
extern uintptr_t _wrap_new_StringVec__SWIG_1_bind_a8cb6205d990f6b5(swig_type_5 arg1);
extern uintptr_t _wrap_new_StringVec__SWIG_2_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern swig_type_6 _wrap_StringVec_size_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern swig_type_7 _wrap_StringVec_capacity_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_StringVec_reserve_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_8 arg2);
extern _Bool _wrap_StringVec_isEmpty_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_StringVec_clear_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_StringVec_add_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_9 arg2);
extern swig_type_10 _wrap_StringVec_get_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_StringVec_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_intgo arg2, swig_type_11 arg3);
extern void _wrap_delete_StringVec_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern uintptr_t _wrap_new_LLVec__SWIG_0_bind_a8cb6205d990f6b5(void);
extern uintptr_t _wrap_new_LLVec__SWIG_1_bind_a8cb6205d990f6b5(swig_type_12 arg1);
extern uintptr_t _wrap_new_LLVec__SWIG_2_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern swig_type_13 _wrap_LLVec_size_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern swig_type_14 _wrap_LLVec_capacity_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_LLVec_reserve_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_15 arg2);
extern _Bool _wrap_LLVec_isEmpty_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_LLVec_clear_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_LLVec_add_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_16 arg2);
extern swig_type_17 _wrap_LLVec_get_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_LLVec_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_intgo arg2, swig_type_18 arg3);
extern void _wrap_delete_LLVec_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Kill_bind_a8cb6205d990f6b5(void);
extern uintptr_t _wrap_new_BindClass_bind_a8cb6205d990f6b5(void);
extern void _wrap_BindClass_Run_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_type_19 arg4, uintptr_t arg5);
extern void _wrap_delete_BindClass_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Condition_Type_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_20 arg2);
extern swig_type_21 _wrap_Condition_Type_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Condition_Condition_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Condition_Condition_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Condition_Actions_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Condition_Actions_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_delete_Condition_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_SubCaller_Indexes_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_SubCaller_Indexes_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_SubCaller_Args_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_SubCaller_Args_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_SubCaller_IsProc_set_bind_a8cb6205d990f6b5(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_SubCaller_IsProc_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern uintptr_t _wrap_new_SubCaller_bind_a8cb6205d990f6b5(void);
extern void _wrap_delete_SubCaller_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Type_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_22 arg2);
extern swig_type_23 _wrap_Action_Type_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Name_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_24 arg2);
extern swig_type_25 _wrap_Action_Name_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_ExpStr_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_ExpStr_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_ExpAct_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_ExpAct_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Params_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_Params_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Args_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_Args_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Condition_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_Condition_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_ID_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Action_ID_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_First_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_First_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Second_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_Second_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Degree_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_Degree_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Value_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_Value_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Indexes_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_Indexes_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Hash_Values_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_Hash_Values_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_IsMutable_set_bind_a8cb6205d990f6b5(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_Action_IsMutable_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Access_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_26 arg2);
extern swig_type_27 _wrap_Action_Access_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_SubCall_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_SubCall_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Integer_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_Integer_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Decimal_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_Decimal_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Action_Thread_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Action_Thread_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern uintptr_t _wrap_new_Action_bind_a8cb6205d990f6b5(void);
extern void _wrap_delete_Action_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Variable_Xtype_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_28 arg2);
extern swig_type_29 _wrap_Variable_Xtype_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Variable_name_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_30 arg2);
extern swig_type_31 _wrap_Variable_name_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Variable_value_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Variable_value_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Variable_cproc_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Variable_cproc_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern uintptr_t _wrap_new_Variable_bind_a8cb6205d990f6b5(void);
extern void _wrap_delete_Variable_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Returner_value_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Returner_value_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Returner_variables_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Returner_variables_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Returner_exp_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Returner_exp_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Returner_Xtype_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_32 arg2);
extern swig_type_33 _wrap_Returner_Xtype_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern uintptr_t _wrap_new_Returner_bind_a8cb6205d990f6b5(void);
extern void _wrap_delete_Returner_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Calc_PREC_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Calc_PREC_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Calc_O_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_34 arg2);
extern swig_type_35 _wrap_Calc_O_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern uintptr_t _wrap_new_Calc_bind_a8cb6205d990f6b5(void);
extern void _wrap_delete_Calc_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Package_ADDON_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_36 arg2);
extern swig_type_37 _wrap_Package_ADDON_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern uintptr_t _wrap_new_Package_bind_a8cb6205d990f6b5(void);
extern void _wrap_delete_Package_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Files_NAME_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_38 arg2);
extern swig_type_39 _wrap_Files_NAME_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_Files_DIR_set_bind_a8cb6205d990f6b5(uintptr_t arg1, swig_type_40 arg2);
extern swig_type_41 _wrap_Files_DIR_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern uintptr_t _wrap_new_Files_bind_a8cb6205d990f6b5(void);
extern void _wrap_delete_Files_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_CliParams_Calc_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_CliParams_Calc_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_CliParams_Package_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_CliParams_Package_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern void _wrap_CliParams_Files_set_bind_a8cb6205d990f6b5(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_CliParams_Files_get_bind_a8cb6205d990f6b5(uintptr_t arg1);
extern uintptr_t _wrap_new_CliParams_bind_a8cb6205d990f6b5(void);
extern void _wrap_delete_CliParams_bind_a8cb6205d990f6b5(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_bind_a8cb6205d990f6b5(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrActionVec uintptr

func (p SwigcptrActionVec) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrActionVec) SwigIsActionVec() {
}

func NewActionVec__SWIG_0() (_swig_ret ActionVec) {
	var swig_r ActionVec
	swig_r = (ActionVec)(SwigcptrActionVec(C._wrap_new_ActionVec__SWIG_0_bind_a8cb6205d990f6b5()))
	return swig_r
}

func NewActionVec__SWIG_1(arg1 int64) (_swig_ret ActionVec) {
	var swig_r ActionVec
	_swig_i_0 := arg1
	swig_r = (ActionVec)(SwigcptrActionVec(C._wrap_new_ActionVec__SWIG_1_bind_a8cb6205d990f6b5(C.swig_type_1(_swig_i_0))))
	return swig_r
}

func NewActionVec__SWIG_2(arg1 ActionVec) (_swig_ret ActionVec) {
	var swig_r ActionVec
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (ActionVec)(SwigcptrActionVec(C._wrap_new_ActionVec__SWIG_2_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewActionVec(a ...interface{}) ActionVec {
	argc := len(a)
	if argc == 0 {
		return NewActionVec__SWIG_0()
	}
	if argc == 1 {
		if _, ok := a[0].(int64); !ok {
			goto check_2
		}
		return NewActionVec__SWIG_1(a[0].(int64))
	}
check_2:
	if argc == 1 {
		return NewActionVec__SWIG_2(a[0].(ActionVec))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrActionVec) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ActionVec_size_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrActionVec) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ActionVec_capacity_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrActionVec) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ActionVec_reserve_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.swig_type_4(_swig_i_1))
}

func (arg1 SwigcptrActionVec) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_ActionVec_isEmpty_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrActionVec) Clear() {
	_swig_i_0 := arg1
	C._wrap_ActionVec_clear_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrActionVec) Add(arg2 Action) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_ActionVec_add_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrActionVec) Get(arg2 int) (_swig_ret Action) {
	var swig_r Action
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Action)(SwigcptrAction(C._wrap_ActionVec_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrActionVec) Set(arg2 int, arg3 Action) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_ActionVec_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func DeleteActionVec(arg1 ActionVec) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_ActionVec_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

type ActionVec interface {
	Swigcptr() uintptr
	SwigIsActionVec()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 Action)
	Get(arg2 int) (_swig_ret Action)
	Set(arg2 int, arg3 Action)
}

type SwigcptrStringVec uintptr

func (p SwigcptrStringVec) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrStringVec) SwigIsStringVec() {
}

func NewStringVec__SWIG_0() (_swig_ret StringVec) {
	var swig_r StringVec
	swig_r = (StringVec)(SwigcptrStringVec(C._wrap_new_StringVec__SWIG_0_bind_a8cb6205d990f6b5()))
	return swig_r
}

func NewStringVec__SWIG_1(arg1 int64) (_swig_ret StringVec) {
	var swig_r StringVec
	_swig_i_0 := arg1
	swig_r = (StringVec)(SwigcptrStringVec(C._wrap_new_StringVec__SWIG_1_bind_a8cb6205d990f6b5(C.swig_type_5(_swig_i_0))))
	return swig_r
}

func NewStringVec__SWIG_2(arg1 StringVec) (_swig_ret StringVec) {
	var swig_r StringVec
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (StringVec)(SwigcptrStringVec(C._wrap_new_StringVec__SWIG_2_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewStringVec(a ...interface{}) StringVec {
	argc := len(a)
	if argc == 0 {
		return NewStringVec__SWIG_0()
	}
	if argc == 1 {
		if _, ok := a[0].(int64); !ok {
			goto check_2
		}
		return NewStringVec__SWIG_1(a[0].(int64))
	}
check_2:
	if argc == 1 {
		return NewStringVec__SWIG_2(a[0].(StringVec))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrStringVec) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_StringVec_size_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrStringVec) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_StringVec_capacity_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrStringVec) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_StringVec_reserve_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.swig_type_8(_swig_i_1))
}

func (arg1 SwigcptrStringVec) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_StringVec_isEmpty_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrStringVec) Clear() {
	_swig_i_0 := arg1
	C._wrap_StringVec_clear_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrStringVec) Add(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_StringVec_add_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), *(*C.swig_type_9)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrStringVec) Get(arg2 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := C._wrap_StringVec_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrStringVec) Set(arg2 int, arg3 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_StringVec_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_11)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func DeleteStringVec(arg1 StringVec) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_StringVec_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

type StringVec interface {
	Swigcptr() uintptr
	SwigIsStringVec()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 string)
	Get(arg2 int) (_swig_ret string)
	Set(arg2 int, arg3 string)
}

type SwigcptrLLVec uintptr

func (p SwigcptrLLVec) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrLLVec) SwigIsLLVec() {
}

func NewLLVec__SWIG_0() (_swig_ret LLVec) {
	var swig_r LLVec
	swig_r = (LLVec)(SwigcptrLLVec(C._wrap_new_LLVec__SWIG_0_bind_a8cb6205d990f6b5()))
	return swig_r
}

func NewLLVec__SWIG_1(arg1 int64) (_swig_ret LLVec) {
	var swig_r LLVec
	_swig_i_0 := arg1
	swig_r = (LLVec)(SwigcptrLLVec(C._wrap_new_LLVec__SWIG_1_bind_a8cb6205d990f6b5(C.swig_type_12(_swig_i_0))))
	return swig_r
}

func NewLLVec__SWIG_2(arg1 LLVec) (_swig_ret LLVec) {
	var swig_r LLVec
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (LLVec)(SwigcptrLLVec(C._wrap_new_LLVec__SWIG_2_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewLLVec(a ...interface{}) LLVec {
	argc := len(a)
	if argc == 0 {
		return NewLLVec__SWIG_0()
	}
	if argc == 1 {
		if _, ok := a[0].(int64); !ok {
			goto check_2
		}
		return NewLLVec__SWIG_1(a[0].(int64))
	}
check_2:
	if argc == 1 {
		return NewLLVec__SWIG_2(a[0].(LLVec))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrLLVec) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_LLVec_size_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrLLVec) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_LLVec_capacity_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrLLVec) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_LLVec_reserve_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.swig_type_15(_swig_i_1))
}

func (arg1 SwigcptrLLVec) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_LLVec_isEmpty_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrLLVec) Clear() {
	_swig_i_0 := arg1
	C._wrap_LLVec_clear_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrLLVec) Add(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_LLVec_add_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.swig_type_16(_swig_i_1))
}

func (arg1 SwigcptrLLVec) Get(arg2 int) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int64)(C._wrap_LLVec_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrLLVec) Set(arg2 int, arg3 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_LLVec_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_type_18(_swig_i_2))
}

func DeleteLLVec(arg1 LLVec) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_LLVec_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

type LLVec interface {
	Swigcptr() uintptr
	SwigIsLLVec()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 int64)
	Get(arg2 int) (_swig_ret int64)
	Set(arg2 int, arg3 int64)
}

const DigitSize int = 1
func Kill() {
	C._wrap_Kill_bind_a8cb6205d990f6b5()
}

type SwigcptrBindClass uintptr

func (p SwigcptrBindClass) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrBindClass) SwigIsBindClass() {
}

func NewBindClass() (_swig_ret BindClass) {
	var swig_r BindClass
	swig_r = (BindClass)(SwigcptrBindClass(C._wrap_new_BindClass_bind_a8cb6205d990f6b5()))
	return swig_r
}

func (arg1 SwigcptrBindClass) Run(arg2 ActionVec, arg3 CliParams, arg4 string, arg5 StringVec) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5.Swigcptr()
	C._wrap_BindClass_Run_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), *(*C.swig_type_19)(unsafe.Pointer(&_swig_i_3)), C.uintptr_t(_swig_i_4))
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
}

func DeleteBindClass(arg1 BindClass) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_BindClass_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

type BindClass interface {
	Swigcptr() uintptr
	SwigIsBindClass()
	Run(arg2 ActionVec, arg3 CliParams, arg4 string, arg5 StringVec)
}

type SwigcptrCondition uintptr

func (p SwigcptrCondition) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCondition) SwigIsCondition() {
}

func (arg1 SwigcptrCondition) SetType(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Condition_Type_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), *(*C.swig_type_20)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrCondition) GetType() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Condition_Type_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrCondition) SetCondition(arg2 ActionVec) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Condition_Condition_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrCondition) GetCondition() (_swig_ret ActionVec) {
	var swig_r ActionVec
	_swig_i_0 := arg1
	swig_r = (ActionVec)(SwigcptrActionVec(C._wrap_Condition_Condition_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrCondition) SetActions(arg2 ActionVec) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Condition_Actions_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrCondition) GetActions() (_swig_ret ActionVec) {
	var swig_r ActionVec
	_swig_i_0 := arg1
	swig_r = (ActionVec)(SwigcptrActionVec(C._wrap_Condition_Actions_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func DeleteCondition(arg1 Condition) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Condition_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

type Condition interface {
	Swigcptr() uintptr
	SwigIsCondition()
	SetType(arg2 string)
	GetType() (_swig_ret string)
	SetCondition(arg2 ActionVec)
	GetCondition() (_swig_ret ActionVec)
	SetActions(arg2 ActionVec)
	GetActions() (_swig_ret ActionVec)
}

type SwigcptrSubCaller uintptr

func (p SwigcptrSubCaller) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSubCaller) SwigIsSubCaller() {
}

func (arg1 SwigcptrSubCaller) SetIndexes(arg2 Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_SubCaller_Indexes_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrSubCaller) GetIndexes() (_swig_ret Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_) {
	var swig_r Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_
	_swig_i_0 := arg1
	swig_r = (Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)(SwigcptrStd_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_(C._wrap_SubCaller_Indexes_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSubCaller) SetArgs(arg2 Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_SubCaller_Args_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrSubCaller) GetArgs() (_swig_ret Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_) {
	var swig_r Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_
	_swig_i_0 := arg1
	swig_r = (Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)(SwigcptrStd_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_(C._wrap_SubCaller_Args_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSubCaller) SetIsProc(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SubCaller_IsProc_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrSubCaller) GetIsProc() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_SubCaller_IsProc_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSubCaller() (_swig_ret SubCaller) {
	var swig_r SubCaller
	swig_r = (SubCaller)(SwigcptrSubCaller(C._wrap_new_SubCaller_bind_a8cb6205d990f6b5()))
	return swig_r
}

func DeleteSubCaller(arg1 SubCaller) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_SubCaller_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

type SubCaller interface {
	Swigcptr() uintptr
	SwigIsSubCaller()
	SetIndexes(arg2 Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)
	GetIndexes() (_swig_ret Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)
	SetArgs(arg2 Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)
	GetArgs() (_swig_ret Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)
	SetIsProc(arg2 bool)
	GetIsProc() (_swig_ret bool)
}

type SwigcptrAction uintptr

func (p SwigcptrAction) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrAction) SwigIsAction() {
}

func (arg1 SwigcptrAction) SetType(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Action_Type_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), *(*C.swig_type_22)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrAction) GetType() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Action_Type_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrAction) SetName(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Action_Name_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), *(*C.swig_type_24)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrAction) GetName() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Action_Name_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrAction) SetExpStr(arg2 StringVec) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_ExpStr_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetExpStr() (_swig_ret StringVec) {
	var swig_r StringVec
	_swig_i_0 := arg1
	swig_r = (StringVec)(SwigcptrStringVec(C._wrap_Action_ExpStr_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetExpAct(arg2 ActionVec) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_ExpAct_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetExpAct() (_swig_ret ActionVec) {
	var swig_r ActionVec
	_swig_i_0 := arg1
	swig_r = (ActionVec)(SwigcptrActionVec(C._wrap_Action_ExpAct_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetParams(arg2 StringVec) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_Params_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetParams() (_swig_ret StringVec) {
	var swig_r StringVec
	_swig_i_0 := arg1
	swig_r = (StringVec)(SwigcptrStringVec(C._wrap_Action_Params_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetArgs(arg2 Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_Args_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetArgs() (_swig_ret Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_) {
	var swig_r Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_
	_swig_i_0 := arg1
	swig_r = (Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)(SwigcptrStd_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_(C._wrap_Action_Args_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetCondition(arg2 Std_vector_Sl_omm_Condition_Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_Condition_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetCondition() (_swig_ret Std_vector_Sl_omm_Condition_Sg_) {
	var swig_r Std_vector_Sl_omm_Condition_Sg_
	_swig_i_0 := arg1
	swig_r = (Std_vector_Sl_omm_Condition_Sg_)(SwigcptrStd_vector_Sl_omm_Condition_Sg_(C._wrap_Action_Condition_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetID(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Action_ID_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrAction) GetID() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Action_ID_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAction) SetFirst(arg2 ActionVec) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_First_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetFirst() (_swig_ret ActionVec) {
	var swig_r ActionVec
	_swig_i_0 := arg1
	swig_r = (ActionVec)(SwigcptrActionVec(C._wrap_Action_First_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetSecond(arg2 ActionVec) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_Second_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetSecond() (_swig_ret ActionVec) {
	var swig_r ActionVec
	_swig_i_0 := arg1
	swig_r = (ActionVec)(SwigcptrActionVec(C._wrap_Action_Second_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetDegree(arg2 ActionVec) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_Degree_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetDegree() (_swig_ret ActionVec) {
	var swig_r ActionVec
	_swig_i_0 := arg1
	swig_r = (ActionVec)(SwigcptrActionVec(C._wrap_Action_Degree_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetValue(arg2 Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_Value_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetValue() (_swig_ret Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_) {
	var swig_r Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_
	_swig_i_0 := arg1
	swig_r = (Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)(SwigcptrStd_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_(C._wrap_Action_Value_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetIndexes(arg2 Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_Indexes_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetIndexes() (_swig_ret Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_) {
	var swig_r Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_
	_swig_i_0 := arg1
	swig_r = (Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)(SwigcptrStd_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_(C._wrap_Action_Indexes_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetHash_Values(arg2 Std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_Hash_Values_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetHash_Values() (_swig_ret Std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg_) {
	var swig_r Std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg_
	_swig_i_0 := arg1
	swig_r = (Std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg_)(SwigcptrStd_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg_(C._wrap_Action_Hash_Values_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetIsMutable(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Action_IsMutable_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrAction) GetIsMutable() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Action_IsMutable_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAction) SetAccess(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Action_Access_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), *(*C.swig_type_26)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrAction) GetAccess() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Action_Access_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrAction) SetSubCall(arg2 Std_vector_Sl_omm_SubCaller_Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_SubCall_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetSubCall() (_swig_ret Std_vector_Sl_omm_SubCaller_Sg_) {
	var swig_r Std_vector_Sl_omm_SubCaller_Sg_
	_swig_i_0 := arg1
	swig_r = (Std_vector_Sl_omm_SubCaller_Sg_)(SwigcptrStd_vector_Sl_omm_SubCaller_Sg_(C._wrap_Action_SubCall_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetInteger(arg2 LLVec) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_Integer_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetInteger() (_swig_ret LLVec) {
	var swig_r LLVec
	_swig_i_0 := arg1
	swig_r = (LLVec)(SwigcptrLLVec(C._wrap_Action_Integer_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetDecimal(arg2 LLVec) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_Decimal_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetDecimal() (_swig_ret LLVec) {
	var swig_r LLVec
	_swig_i_0 := arg1
	swig_r = (LLVec)(SwigcptrLLVec(C._wrap_Action_Decimal_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAction) SetThread(arg2 Std_shared_ptr_Sl_std_future_Sl_omm_Returner_Sg__Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Action_Thread_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAction) GetThread() (_swig_ret Std_shared_ptr_Sl_std_future_Sl_omm_Returner_Sg__Sg_) {
	var swig_r Std_shared_ptr_Sl_std_future_Sl_omm_Returner_Sg__Sg_
	_swig_i_0 := arg1
	swig_r = (Std_shared_ptr_Sl_std_future_Sl_omm_Returner_Sg__Sg_)(SwigcptrStd_shared_ptr_Sl_std_future_Sl_omm_Returner_Sg__Sg_(C._wrap_Action_Thread_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewAction() (_swig_ret Action) {
	var swig_r Action
	swig_r = (Action)(SwigcptrAction(C._wrap_new_Action_bind_a8cb6205d990f6b5()))
	return swig_r
}

func DeleteAction(arg1 Action) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Action_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

type Action interface {
	Swigcptr() uintptr
	SwigIsAction()
	SetType(arg2 string)
	GetType() (_swig_ret string)
	SetName(arg2 string)
	GetName() (_swig_ret string)
	SetExpStr(arg2 StringVec)
	GetExpStr() (_swig_ret StringVec)
	SetExpAct(arg2 ActionVec)
	GetExpAct() (_swig_ret ActionVec)
	SetParams(arg2 StringVec)
	GetParams() (_swig_ret StringVec)
	SetArgs(arg2 Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)
	GetArgs() (_swig_ret Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)
	SetCondition(arg2 Std_vector_Sl_omm_Condition_Sg_)
	GetCondition() (_swig_ret Std_vector_Sl_omm_Condition_Sg_)
	SetID(arg2 int)
	GetID() (_swig_ret int)
	SetFirst(arg2 ActionVec)
	GetFirst() (_swig_ret ActionVec)
	SetSecond(arg2 ActionVec)
	GetSecond() (_swig_ret ActionVec)
	SetDegree(arg2 ActionVec)
	GetDegree() (_swig_ret ActionVec)
	SetValue(arg2 Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)
	GetValue() (_swig_ret Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)
	SetIndexes(arg2 Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)
	GetIndexes() (_swig_ret Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_)
	SetHash_Values(arg2 Std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg_)
	GetHash_Values() (_swig_ret Std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg_)
	SetIsMutable(arg2 bool)
	GetIsMutable() (_swig_ret bool)
	SetAccess(arg2 string)
	GetAccess() (_swig_ret string)
	SetSubCall(arg2 Std_vector_Sl_omm_SubCaller_Sg_)
	GetSubCall() (_swig_ret Std_vector_Sl_omm_SubCaller_Sg_)
	SetInteger(arg2 LLVec)
	GetInteger() (_swig_ret LLVec)
	SetDecimal(arg2 LLVec)
	GetDecimal() (_swig_ret LLVec)
	SetThread(arg2 Std_shared_ptr_Sl_std_future_Sl_omm_Returner_Sg__Sg_)
	GetThread() (_swig_ret Std_shared_ptr_Sl_std_future_Sl_omm_Returner_Sg__Sg_)
}

type SwigcptrVariable uintptr

func (p SwigcptrVariable) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVariable) SwigIsVariable() {
}

func (arg1 SwigcptrVariable) SetXtype(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Variable_Xtype_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), *(*C.swig_type_28)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrVariable) GetXtype() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Variable_Xtype_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrVariable) SetName(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Variable_name_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), *(*C.swig_type_30)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrVariable) GetName() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Variable_name_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrVariable) SetValue(arg2 ActionVec) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Variable_value_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrVariable) GetValue() (_swig_ret ActionVec) {
	var swig_r ActionVec
	_swig_i_0 := arg1
	swig_r = (ActionVec)(SwigcptrActionVec(C._wrap_Variable_value_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVariable) SetCproc(arg2 Std_function_Sl_omm_Returner_Sp_omm_Action_Sc_omm_CliParams_Sc_std_map_Sl_std_string_Sc_omm_Variable_Sg__Sc_std_deque_Sl_std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg__Sg__Sc_std_string_SP__Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Variable_cproc_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrVariable) GetCproc() (_swig_ret Std_function_Sl_omm_Returner_Sp_omm_Action_Sc_omm_CliParams_Sc_std_map_Sl_std_string_Sc_omm_Variable_Sg__Sc_std_deque_Sl_std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg__Sg__Sc_std_string_SP__Sg_) {
	var swig_r Std_function_Sl_omm_Returner_Sp_omm_Action_Sc_omm_CliParams_Sc_std_map_Sl_std_string_Sc_omm_Variable_Sg__Sc_std_deque_Sl_std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg__Sg__Sc_std_string_SP__Sg_
	_swig_i_0 := arg1
	swig_r = (Std_function_Sl_omm_Returner_Sp_omm_Action_Sc_omm_CliParams_Sc_std_map_Sl_std_string_Sc_omm_Variable_Sg__Sc_std_deque_Sl_std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg__Sg__Sc_std_string_SP__Sg_)(SwigcptrStd_function_Sl_omm_Returner_Sp_omm_Action_Sc_omm_CliParams_Sc_std_map_Sl_std_string_Sc_omm_Variable_Sg__Sc_std_deque_Sl_std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg__Sg__Sc_std_string_SP__Sg_(C._wrap_Variable_cproc_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewVariable() (_swig_ret Variable) {
	var swig_r Variable
	swig_r = (Variable)(SwigcptrVariable(C._wrap_new_Variable_bind_a8cb6205d990f6b5()))
	return swig_r
}

func DeleteVariable(arg1 Variable) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Variable_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

type Variable interface {
	Swigcptr() uintptr
	SwigIsVariable()
	SetXtype(arg2 string)
	GetXtype() (_swig_ret string)
	SetName(arg2 string)
	GetName() (_swig_ret string)
	SetValue(arg2 ActionVec)
	GetValue() (_swig_ret ActionVec)
	SetCproc(arg2 Std_function_Sl_omm_Returner_Sp_omm_Action_Sc_omm_CliParams_Sc_std_map_Sl_std_string_Sc_omm_Variable_Sg__Sc_std_deque_Sl_std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg__Sg__Sc_std_string_SP__Sg_)
	GetCproc() (_swig_ret Std_function_Sl_omm_Returner_Sp_omm_Action_Sc_omm_CliParams_Sc_std_map_Sl_std_string_Sc_omm_Variable_Sg__Sc_std_deque_Sl_std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg__Sg__Sc_std_string_SP__Sg_)
}

type SwigcptrReturner uintptr

func (p SwigcptrReturner) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrReturner) SwigIsReturner() {
}

func (arg1 SwigcptrReturner) SetValue(arg2 StringVec) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Returner_value_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrReturner) GetValue() (_swig_ret StringVec) {
	var swig_r StringVec
	_swig_i_0 := arg1
	swig_r = (StringVec)(SwigcptrStringVec(C._wrap_Returner_value_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrReturner) SetVariables(arg2 Std_map_Sl_std_string_Sc_omm_Variable_Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Returner_variables_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrReturner) GetVariables() (_swig_ret Std_map_Sl_std_string_Sc_omm_Variable_Sg_) {
	var swig_r Std_map_Sl_std_string_Sc_omm_Variable_Sg_
	_swig_i_0 := arg1
	swig_r = (Std_map_Sl_std_string_Sc_omm_Variable_Sg_)(SwigcptrStd_map_Sl_std_string_Sc_omm_Variable_Sg_(C._wrap_Returner_variables_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrReturner) SetExp(arg2 Action) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Returner_exp_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrReturner) GetExp() (_swig_ret Action) {
	var swig_r Action
	_swig_i_0 := arg1
	swig_r = (Action)(SwigcptrAction(C._wrap_Returner_exp_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrReturner) SetXtype(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Returner_Xtype_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), *(*C.swig_type_32)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrReturner) GetXtype() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Returner_Xtype_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func NewReturner() (_swig_ret Returner) {
	var swig_r Returner
	swig_r = (Returner)(SwigcptrReturner(C._wrap_new_Returner_bind_a8cb6205d990f6b5()))
	return swig_r
}

func DeleteReturner(arg1 Returner) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Returner_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

type Returner interface {
	Swigcptr() uintptr
	SwigIsReturner()
	SetValue(arg2 StringVec)
	GetValue() (_swig_ret StringVec)
	SetVariables(arg2 Std_map_Sl_std_string_Sc_omm_Variable_Sg_)
	GetVariables() (_swig_ret Std_map_Sl_std_string_Sc_omm_Variable_Sg_)
	SetExp(arg2 Action)
	GetExp() (_swig_ret Action)
	SetXtype(arg2 string)
	GetXtype() (_swig_ret string)
}

type SwigcptrCalc uintptr

func (p SwigcptrCalc) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCalc) SwigIsCalc() {
}

func (arg1 SwigcptrCalc) SetPREC(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Calc_PREC_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrCalc) GetPREC() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Calc_PREC_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrCalc) SetO(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Calc_O_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), *(*C.swig_type_34)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrCalc) GetO() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Calc_O_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func NewCalc() (_swig_ret Calc) {
	var swig_r Calc
	swig_r = (Calc)(SwigcptrCalc(C._wrap_new_Calc_bind_a8cb6205d990f6b5()))
	return swig_r
}

func DeleteCalc(arg1 Calc) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Calc_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

type Calc interface {
	Swigcptr() uintptr
	SwigIsCalc()
	SetPREC(arg2 int)
	GetPREC() (_swig_ret int)
	SetO(arg2 string)
	GetO() (_swig_ret string)
}

type SwigcptrPackage uintptr

func (p SwigcptrPackage) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrPackage) SwigIsPackage() {
}

func (arg1 SwigcptrPackage) SetADDON(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Package_ADDON_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), *(*C.swig_type_36)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrPackage) GetADDON() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Package_ADDON_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func NewPackage() (_swig_ret Package) {
	var swig_r Package
	swig_r = (Package)(SwigcptrPackage(C._wrap_new_Package_bind_a8cb6205d990f6b5()))
	return swig_r
}

func DeletePackage(arg1 Package) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Package_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

type Package interface {
	Swigcptr() uintptr
	SwigIsPackage()
	SetADDON(arg2 string)
	GetADDON() (_swig_ret string)
}

type SwigcptrFiles uintptr

func (p SwigcptrFiles) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFiles) SwigIsFiles() {
}

func (arg1 SwigcptrFiles) SetNAME(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Files_NAME_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), *(*C.swig_type_38)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrFiles) GetNAME() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Files_NAME_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrFiles) SetDIR(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Files_DIR_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), *(*C.swig_type_40)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrFiles) GetDIR() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Files_DIR_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func NewFiles() (_swig_ret Files) {
	var swig_r Files
	swig_r = (Files)(SwigcptrFiles(C._wrap_new_Files_bind_a8cb6205d990f6b5()))
	return swig_r
}

func DeleteFiles(arg1 Files) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Files_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

type Files interface {
	Swigcptr() uintptr
	SwigIsFiles()
	SetNAME(arg2 string)
	GetNAME() (_swig_ret string)
	SetDIR(arg2 string)
	GetDIR() (_swig_ret string)
}

type SwigcptrCliParams uintptr

func (p SwigcptrCliParams) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCliParams) SwigIsCliParams() {
}

func (arg1 SwigcptrCliParams) SetCalc(arg2 Calc) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_CliParams_Calc_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrCliParams) GetCalc() (_swig_ret Calc) {
	var swig_r Calc
	_swig_i_0 := arg1
	swig_r = (Calc)(SwigcptrCalc(C._wrap_CliParams_Calc_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrCliParams) SetPackage(arg2 Package) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_CliParams_Package_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrCliParams) GetPackage() (_swig_ret Package) {
	var swig_r Package
	_swig_i_0 := arg1
	swig_r = (Package)(SwigcptrPackage(C._wrap_CliParams_Package_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrCliParams) SetFiles(arg2 Files) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_CliParams_Files_set_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrCliParams) GetFiles() (_swig_ret Files) {
	var swig_r Files
	_swig_i_0 := arg1
	swig_r = (Files)(SwigcptrFiles(C._wrap_CliParams_Files_get_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewCliParams() (_swig_ret CliParams) {
	var swig_r CliParams
	swig_r = (CliParams)(SwigcptrCliParams(C._wrap_new_CliParams_bind_a8cb6205d990f6b5()))
	return swig_r
}

func DeleteCliParams(arg1 CliParams) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_CliParams_bind_a8cb6205d990f6b5(C.uintptr_t(_swig_i_0))
}

type CliParams interface {
	Swigcptr() uintptr
	SwigIsCliParams()
	SetCalc(arg2 Calc)
	GetCalc() (_swig_ret Calc)
	SetPackage(arg2 Package)
	GetPackage() (_swig_ret Package)
	SetFiles(arg2 Files)
	GetFiles() (_swig_ret Files)
}


type SwigcptrStd_map_Sl_std_string_Sc_omm_Variable_Sg_ uintptr
type Std_map_Sl_std_string_Sc_omm_Variable_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_map_Sl_std_string_Sc_omm_Variable_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_omm_SubCaller_Sg_ uintptr
type Std_vector_Sl_omm_SubCaller_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_omm_SubCaller_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_function_Sl_omm_Returner_Sp_omm_Action_Sc_omm_CliParams_Sc_std_map_Sl_std_string_Sc_omm_Variable_Sg__Sc_std_deque_Sl_std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg__Sg__Sc_std_string_SP__Sg_ uintptr
type Std_function_Sl_omm_Returner_Sp_omm_Action_Sc_omm_CliParams_Sc_std_map_Sl_std_string_Sc_omm_Variable_Sg__Sc_std_deque_Sl_std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg__Sg__Sc_std_string_SP__Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_function_Sl_omm_Returner_Sp_omm_Action_Sc_omm_CliParams_Sc_std_map_Sl_std_string_Sc_omm_Variable_Sg__Sc_std_deque_Sl_std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg__Sg__Sc_std_string_SP__Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg_ uintptr
type Std_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_map_Sl_std_string_Sc_std_vector_Sl_omm_Action_Sg__Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_ uintptr
type Std_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_std_vector_Sl_omm_Action_Sg__Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_omm_Condition_Sg_ uintptr
type Std_vector_Sl_omm_Condition_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_omm_Condition_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_shared_ptr_Sl_std_future_Sl_omm_Returner_Sg__Sg_ uintptr
type Std_shared_ptr_Sl_std_future_Sl_omm_Returner_Sg__Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_shared_ptr_Sl_std_future_Sl_omm_Returner_Sg__Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

