#include <fstream>
#include "../callspec.h"

//this is a generator file that that generate the switch statement that passes the arguments to a dll function

int main() {
    std::ofstream out;
    out.open("ffi/callswitch.h");

    //put the warning
    out << "//This file was automatically generated by ffi/generate/wingenerate_args.cc to generate the switch statement that calls a dll function\n//PLEASE DO NOT EDIT THIS FILE!\n";

    //include windows.h
    out << "#include <windows.h>\n";

    //function declaration
    out << "long long int callswitch(FARPROC proc, int argc, void** argv) {\n";

    //perform the switch
    out << "switch (argc) {\n";

    for (unsigned int i = 0; i <= MAX_ARGC; ++i) {
        out << "case " << i << ":\n";
        out << "return proc(";

        for (unsigned int o = 0; o < i; ++o) {
            out << "argv[" << o << "]";
            if (o + 1 != i) out << ","; //if it is the last argument, do not put a comma
        }

        out << ");\n";
    }

    out << "}\n" << "}";
}