#ifndef FALSEY_VAL_HPP_
#define FALSEY_VAL_HPP_

#include "json.hpp"
using namespace std;

const json falseyVal = {
  {"Type", "falsey"},
  {"Name", ""},
  {"ExpStr", json::parse("[\"undefined\"]")},
  {"ExpAct", "[]"_json},
  {"Params", "[]"_json},
  {"Args", "[]"_json},
  {"Condition", "[]"_json},
  {"ID", 41},
  {"First", "[]"_json},
  {"Second", "[]"_json},
  {"Degree", "[]"_json},
  {"Value", "[[]]"_json},
  {"Indexes", "[[]]"_json},
  {"Index_Type", ""},
  {"Hash_Values", "{}"_json},
  {"ValueType", {{
    {"Type", "falsey"},
    {"Name", ""},
    {"ExpStr", json::parse("[\"undefined\"]")},
    {"ExpAct", "[]"_json},
    {"Params", "[]"_json},
    {"Args", "[]"_json},
    {"Condition", "[]"_json},
    {"ID", 41},
    {"First", "[]"_json},
    {"Second", "[]"_json},
    {"Degree", "[]"_json},
    {"Value", "[[]]"_json},
    {"Indexes", "[[]]"_json},
    {"Index_Type", ""},
    {"Hash_Values", "{}"_json},
    {"ValueType", "[]"_json}
  }}}
}
, trueRet = {
  {"Type", "boolean"},
  {"Name", ""},
  {"ExpStr", json::parse("[\"true\"]")},
  {"ExpAct", "[]"_json},
  {"Params", "[]"_json},
  {"Args", "[]"_json},
  {"Condition", "[]"_json},
  {"ID", 41},
  {"First", "[]"_json},
  {"Second", "[]"_json},
  {"Degree", "[]"_json},
  {"Value", "[[]]"_json},
  {"Indexes", "[[]]"_json},
  {"Index_Type", ""},
  {"Hash_Values", "{}"_json},
  {"ValueType", {{
    {"Type", "boolean"},
    {"Name", ""},
    {"ExpStr", json::parse("[\"true\"]")},
    {"ExpAct", "[]"_json},
    {"Params", "[]"_json},
    {"Args", "[]"_json},
    {"Condition", "[]"_json},
    {"ID", 41},
    {"First", "[]"_json},
    {"Second", "[]"_json},
    {"Degree", "[]"_json},
    {"Value", "[[]]"_json},
    {"Indexes", "[[]]"_json},
    {"Index_Type", ""},
    {"Hash_Values", "{}"_json},
    {"ValueType", "[]"_json}
  }}}
}
, falseRet = {
  {"Type", "boolean"},
  {"Name", ""},
  {"ExpStr", json::parse("[\"false\"]")},
  {"ExpAct", "[]"_json},
  {"Params", "[]"_json},
  {"Args", "[]"_json},
  {"Condition", "[]"_json},
  {"ID", 41},
  {"First", "[]"_json},
  {"Second", "[]"_json},
  {"Degree", "[]"_json},
  {"Value", "[[]]"_json},
  {"Indexes", "[[]]"_json},
  {"Index_Type", ""},
  {"Hash_Values", "{}"_json},
  {"ValueType", {{
    {"Type", "boolean"},
    {"Name", ""},
    {"ExpStr", json::parse("[\"false\"]")},
    {"ExpAct", "[]"_json},
    {"Params", "[]"_json},
    {"Args", "[]"_json},
    {"Condition", "[]"_json},
    {"ID", 41},
    {"First", "[]"_json},
    {"Second", "[]"_json},
    {"Degree", "[]"_json},
    {"Value", "[[]]"_json},
    {"Indexes", "[[]]"_json},
    {"Index_Type", ""},
    {"Hash_Values", "{}"_json},
    {"ValueType", "[]"_json}
  }}}
}
, zero = {
  {"Type", "number"},
  {"Name", ""},
  {"ExpStr", json::parse("[\"0\"]")},
  {"ExpAct", "[]"_json},
  {"Params", "[]"_json},
  {"Args", "[]"_json},
  {"Condition", "[]"_json},
  {"ID", 39},
  {"First", "[]"_json},
  {"Second", "[]"_json},
  {"Degree", "[]"_json},
  {"Value", "[[]]"_json},
  {"Indexes", "[[]]"_json},
  {"Index_Type", ""},
  {"Hash_Values", "{}"_json},
  {"ValueType", {{
    {"Type", "number"},
    {"Name", ""},
    {"ExpStr", json::parse("[\"0\"]")},
    {"ExpAct", "[]"_json},
    {"Params", "[]"_json},
    {"Args", "[]"_json},
    {"Condition", "[]"_json},
    {"ID", 39},
    {"First", "[]"_json},
    {"Second", "[]"_json},
    {"Degree", "[]"_json},
    {"Value", "[[]]"_json},
    {"Indexes", "[[]]"_json},
    {"Index_Type", ""},
    {"Hash_Values", "{}"_json},
    {"ValueType", "[]"_json}
  }}}
}
, val1 = {
  {"Type", "number"},
  {"Name", ""},
  {"ExpStr", json::parse("[\"1\"]")},
  {"ExpAct", "[]"_json},
  {"Params", "[]"_json},
  {"Args", "[]"_json},
  {"Condition", "[]"_json},
  {"ID", 39},
  {"First", "[]"_json},
  {"Second", "[]"_json},
  {"Degree", "[]"_json},
  {"Value", "[[]]"_json},
  {"Indexes", "[[]]"_json},
  {"Index_Type", ""},
  {"Hash_Values", "{}"_json},
  {"ValueType", {{
    {"Type", "number"},
    {"Name", ""},
    {"ExpStr", json::parse("[\"1\"]")},
    {"ExpAct", "[]"_json},
    {"Params", "[]"_json},
    {"Args", "[]"_json},
    {"Condition", "[]"_json},
    {"ID", 39},
    {"First", "[]"_json},
    {"Second", "[]"_json},
    {"Degree", "[]"_json},
    {"Value", "[[]]"_json},
    {"Indexes", "[[]]"_json},
    {"Index_Type", ""},
    {"Hash_Values", "{}"_json},
    {"ValueType", "[]"_json}
  }}}
}
, valn1= {
  {"Type", "number"},
  {"Name", ""},
  {"ExpStr", json::parse("[\"-1\"]")},
  {"ExpAct", "[]"_json},
  {"Params", "[]"_json},
  {"Args", "[]"_json},
  {"Condition", "[]"_json},
  {"ID", 39},
  {"First", "[]"_json},
  {"Second", "[]"_json},
  {"Degree", "[]"_json},
  {"Value", "[[]]"_json},
  {"Indexes", "[[]]"_json},
  {"Index_Type", ""},
  {"Hash_Values", "{}"_json},
  {"ValueType", {{
    {"Type", "number"},
    {"Name", ""},
    {"ExpStr", json::parse("[\"-1\"]")},
    {"ExpAct", "[]"_json},
    {"Params", "[]"_json},
    {"Args", "[]"_json},
    {"Condition", "[]"_json},
    {"ID", 39},
    {"First", "[]"_json},
    {"Second", "[]"_json},
    {"Degree", "[]"_json},
    {"Value", "[[]]"_json},
    {"Indexes", "[[]]"_json},
    {"Index_Type", ""},
    {"Hash_Values", "{}"_json},
    {"ValueType", "[]"_json}
  }}}
};

#endif
